[project]
name = "shadipto-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "pandas>=2.3.0",
    "plotly>=6.2.0",
    "streamlit>=1.46.1",
]
